//! Raw FFI bindings for WPE libraries.
//!
//! Generated by bindgen from:
//! - libwpe (wpe-1.0): Core view-backend abstraction
//! - wpebackend-fdo (wpe-fdo-1.0): FreeDesktop.org EGL backend (legacy)
//! - wpe-platform (wpe-platform-2.0): New WPE Platform API with dma-buf
//! - wpe-webkit (wpe-webkit-2.0): WebKit browser engine
//! - EGL: For DMA-BUF export

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include generated libwpe bindings
include!(concat!(env!("OUT_DIR"), "/wpe_sys.rs"));

// EGL bindings for DMA-BUF export
pub mod egl {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    include!(concat!(env!("OUT_DIR"), "/egl_sys.rs"));

    // DMA-BUF export extension function types
    pub type PFNEGLEXPORTDMABUFIMAGEMESAPROC = unsafe extern "C" fn(
        dpy: EGLDisplay,
        image: EGLImageKHR,
        fds: *mut libc::c_int,
        strides: *mut i32,
        offsets: *mut i32,
    ) -> EGLBoolean;

    pub type PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC = unsafe extern "C" fn(
        dpy: EGLDisplay,
        image: EGLImageKHR,
        fourcc: *mut libc::c_int,
        num_planes: *mut libc::c_int,
        modifiers: *mut u64,
    ) -> EGLBoolean;

    // DMA-BUF format constants (common fourcc codes)
    pub const DRM_FORMAT_ARGB8888: u32 = 0x34325241; // 'AR24'
    pub const DRM_FORMAT_XRGB8888: u32 = 0x34325258; // 'XR24'
    pub const DRM_FORMAT_ABGR8888: u32 = 0x34324241; // 'AB24'
    pub const DRM_FORMAT_XBGR8888: u32 = 0x34324258; // 'XB24'
}

// wpe-fdo bindings (legacy - for fallback/SHM mode)
pub mod fdo {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    // Re-export wpe_view_backend from parent
    pub use super::wpe_view_backend;

    include!(concat!(env!("OUT_DIR"), "/wpe_fdo_sys.rs"));
}

// WPE Platform API bindings (new - for dma-buf GPU rendering)
#[cfg(wpe_platform_available)]
pub mod platform {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]
    #![allow(improper_ctypes)]

    include!(concat!(env!("OUT_DIR"), "/wpe_platform_sys.rs"));

    // GLib main context functions (not always in generated bindings)
    #[repr(C)]
    pub struct GMainContext {
        _unused: [u8; 0],
    }

    extern "C" {
        pub fn g_main_context_default() -> *mut GMainContext;
        pub fn g_main_context_get_thread_default() -> *mut GMainContext;
        pub fn g_main_context_iteration(context: *mut GMainContext, may_block: i32) -> i32;
    }
}

// wpe-webkit bindings (WebKitWebView, etc.)
pub mod webkit {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]
    #![allow(improper_ctypes)]

    // Re-export wpe_view_backend from parent to use the same type
    pub use super::wpe_view_backend;

    include!(concat!(env!("OUT_DIR"), "/wpe_webkit_sys.rs"));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_wpe_types_exist() {
        // Just verify the types are generated
        let _: *mut wpe_view_backend = std::ptr::null_mut();
    }
}
