/* Auto-generated by cbindgen. Do not edit. */
/* Neomacs Display Engine C FFI */


#ifndef NEOMACS_DISPLAY_H
#define NEOMACS_DISPLAY_H

/* Warning: this file was auto-generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Backend type selection
 */
typedef enum BackendType {
  /**
   * GTK4/GSK GPU-accelerated backend
   */
  BACKEND_TYPE_GTK4 = 0,
  /**
   * Terminal/TTY backend
   */
  BACKEND_TYPE_TTY = 1,
} BackendType;

/**
 * Initialize the display engine
 *
 * # Safety
 * Returns a pointer to NeomacsDisplay that must be freed with neomacs_display_shutdown.
 */
struct NeomacsDisplay *neomacs_display_init(enum BackendType backend);

/**
 * Shutdown the display engine
 *
 * # Safety
 * The handle must have been returned by neomacs_display_init.
 */
void neomacs_display_shutdown(struct NeomacsDisplay *handle);

/**
 * Resize the display
 */
void neomacs_display_resize(struct NeomacsDisplay *handle, int width, int height);

/**
 * Begin building a new frame
 */
void neomacs_display_begin_frame(struct NeomacsDisplay *handle);

/**
 * Add a window to the current frame
 */
void neomacs_display_add_window(struct NeomacsDisplay *handle,
                                int windowId,
                                float x,
                                float y,
                                float width,
                                float height,
                                uint32_t bgColor,
                                int selected);

/**
 * Set cursor for the most recently added window
 */
void neomacs_display_set_cursor(struct NeomacsDisplay *handle,
                                float x,
                                float y,
                                float width,
                                float height,
                                int style,
                                uint32_t color,
                                int visible);

/**
 * Begin a new glyph row for the current window
 */
void neomacs_display_begin_row(struct NeomacsDisplay *handle,
                               int y,
                               int height,
                               int ascent,
                               int modeLine,
                               int headerLine);

/**
 * Add a character glyph to the current row
 */
void neomacs_display_add_char_glyph(struct NeomacsDisplay *handle,
                                    uint32_t charcode,
                                    uint32_t faceId,
                                    int pixelWidth,
                                    int ascent,
                                    int descent);

/**
 * Add a stretch (whitespace) glyph to the current row
 */
void neomacs_display_add_stretch_glyph(struct NeomacsDisplay *handle,
                                       int pixelWidth,
                                       int height,
                                       uint32_t faceId);

/**
 * Add an image glyph to the current row
 */
void neomacs_display_add_image_glyph(struct NeomacsDisplay *handle,
                                     uint32_t imageId,
                                     int pixelWidth,
                                     int pixelHeight);

/**
 * End the current row
 */
void neomacs_display_end_row(struct NeomacsDisplay *handle);

/**
 * Load an image from file path
 * Returns image_id on success, 0 on failure
 */
uint32_t neomacs_display_load_image(struct NeomacsDisplay *handle, const char *path);

/**
 * Add a video glyph to the current row
 */
void neomacs_display_add_video_glyph(struct NeomacsDisplay *handle,
                                     uint32_t videoId,
                                     int pixelWidth,
                                     int pixelHeight);

/**
 * Load a video from URI
 * Returns video_id on success, 0 on failure
 */
uint32_t neomacs_display_load_video(struct NeomacsDisplay *handle, const char *uri);

/**
 * Play a loaded video
 */
int neomacs_display_video_play(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Pause a video
 */
int neomacs_display_video_pause(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Stop a video
 */
int neomacs_display_video_stop(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * End frame and render
 */
int neomacs_display_end_frame(struct NeomacsDisplay *handle);

/**
 * Start smooth scroll animation
 */
void neomacs_display_smooth_scroll(struct NeomacsDisplay *handle,
                                   int windowId,
                                   float fromOffset,
                                   float toOffset);

/**
 * Reset cursor blink (call when cursor moves)
 */
void neomacs_display_reset_cursor_blink(struct NeomacsDisplay *handle);

/**
 * Check if animations are active
 */
int neomacs_display_has_animations(struct NeomacsDisplay *handle);

/**
 * Get backend name
 */
const char *neomacs_display_backend_name(struct NeomacsDisplay *handle);

/**
 * Check if backend is initialized
 */
int neomacs_display_is_initialized(struct NeomacsDisplay *handle);

#endif  /* NEOMACS_DISPLAY_H */
