/* Auto-generated by cbindgen. Do not edit. */
/* Neomacs Display Engine C FFI */


#ifndef NEOMACS_DISPLAY_H
#define NEOMACS_DISPLAY_H

/* Warning: this file was auto-generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/**
 * Modifier flags matching Emacs.
 */
#define NEOMACS_SHIFT_MASK (1 << 0)

#define NEOMACS_CTRL_MASK (1 << 1)

#define NEOMACS_META_MASK (1 << 2)

#define NEOMACS_SUPER_MASK (1 << 3)

/**
 * Event kinds for NeomacsInputEvent.kind
 */
#define NEOMACS_EVENT_KEY_PRESS     1
#define NEOMACS_EVENT_KEY_RELEASE   2
#define NEOMACS_EVENT_MOUSE_PRESS   3
#define NEOMACS_EVENT_MOUSE_RELEASE 4
#define NEOMACS_EVENT_MOUSE_MOVE    5
#define NEOMACS_EVENT_SCROLL        6
#define NEOMACS_EVENT_RESIZE        7
#define NEOMACS_EVENT_CLOSE_REQUEST 8
#define NEOMACS_EVENT_FOCUS_IN      9
#define NEOMACS_EVENT_FOCUS_OUT     10
#define NEOMACS_EVENT_IMAGE_DIMENSIONS_READY 11
#define NEOMACS_EVENT_TERMINAL_EXITED 12
#define NEOMACS_EVENT_MENU_SELECTION 13
#define NEOMACS_EVENT_FILE_DROP 14
#define NEOMACS_EVENT_TERMINAL_TITLE_CHANGED 15

#define DRM_FORMAT_ARGB8888 875713089

#define DRM_FORMAT_XRGB8888 875713112

#define DRM_FORMAT_ABGR8888 875708993

#define DRM_FORMAT_XBGR8888 875709016


/**
 * Modifier flags matching Emacs.
 */
#define NEOMACS_SHIFT_MASK (1 << 0)

#define NEOMACS_CTRL_MASK (1 << 1)

#define NEOMACS_META_MASK (1 << 2)

#define NEOMACS_SUPER_MASK (1 << 3)





















#define DRM_FORMAT_ARGB8888 875713089

#define DRM_FORMAT_ARGB8888 875713089

#define DRM_FORMAT_XRGB8888 875713112

#define DRM_FORMAT_XRGB8888 875713112

#define DRM_FORMAT_ABGR8888 875708993

#define DRM_FORMAT_ABGR8888 875708993

#define DRM_FORMAT_XBGR8888 875709016

#define DRM_FORMAT_XBGR8888 875709016

#define DRM_FORMAT_RGBA8888 875708754

#define DRM_FORMAT_RGBX8888 875714642

#define DRM_FORMAT_BGRA8888 875708738

#define DRM_FORMAT_BGRX8888 875714626

#define DRM_FORMAT_NV12 842094158

#define DRM_FORMAT_YUV420 842093913

/**
 * Linear modifier (no tiling)
 */
#define DRM_FORMAT_MOD_LINEAR 0

/**
 * Invalid modifier
 */
#define DRM_FORMAT_MOD_INVALID 72057594037927935

#define VA_EXPORT_SURFACE_READ_ONLY 1

#define VA_EXPORT_SURFACE_SEPARATE_LAYERS 4

#define VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2 1073741824

/**
 * Backend type selection
 */
typedef enum BackendType {
  /**
   * Terminal/TTY backend
   */
  BACKEND_TYPE_TTY = 0,
  /**
   * Winit/wgpu GPU-accelerated backend
   */
  BACKEND_TYPE_WGPU = 1,
} BackendType;

/**
 * Type for the resize callback function pointer from C
 */
typedef void (*ResizeCallbackFn)(void *user_data, int width, int height);

/**
 * Input event structure passed to C.
 */
typedef struct NeomacsInputEvent {
  uint32_t kind;
  uint32_t windowId;
  uint64_t timestamp;
  int32_t x;
  int32_t y;
  uint32_t keycode;
  uint32_t keysym;
  uint32_t modifiers;
  uint32_t button;
  float scrollDeltaX;
  float scrollDeltaY;
  uint32_t pixelPrecise;
  uint32_t width;
  uint32_t height;
  /** Target frame pointer for child frame mouse event routing (0 = parent frame) */
  uint64_t targetFrameId;
} NeomacsInputEvent;

#define VA_STATUS_SUCCESS 0

#define VA_INVALID_SURFACE 4294967295

/* Forward declaration of opaque display handle type */
struct NeomacsDisplay;

/* Note: neomacs_display_init() has been removed - use neomacs_display_init_threaded() instead */

/**
 * Shutdown the display engine
 *
 * # Safety
 * The handle must have been returned by neomacs_display_init_threaded.
 */
void neomacs_display_shutdown(struct NeomacsDisplay *handle);

/* Note: neomacs_display_get_event_fd() has been removed - use neomacs_display_get_threaded_wakeup_fd() instead */

/**
 * Resize the display
 */
void neomacs_display_resize(struct NeomacsDisplay *handle, int width, int height);

/**
 * Begin building a new frame
 */
void neomacs_display_begin_frame(struct NeomacsDisplay *handle);

/**
 * Add a window to the current frame
 */
void neomacs_display_add_window(struct NeomacsDisplay *handle,
                                int windowId,
                                float x,
                                float y,
                                float width,
                                float height,
                                uint32_t bgColor,
                                int selected);

/**
 * Set cursor for a specific window
 */
void neomacs_display_set_cursor(struct NeomacsDisplay *handle,
                                int windowId,
                                float x,
                                float y,
                                float width,
                                float height,
                                int style,
                                uint32_t color,
                                int visible);

/**
 * Set inverse video info for a filled box cursor.
 * Provides cursor bg color (rect) and cursor fg color (text under cursor).
 * Colors are in 0xAARRGGBB format.
 */
void neomacs_display_set_cursor_inverse(struct NeomacsDisplay *handle,
                                        float x,
                                        float y,
                                        float width,
                                        float height,
                                        uint32_t cursor_bg_rgba,
                                        uint32_t cursor_fg_rgba);

/**
 * Draw a border rectangle (for window dividers)
 */
void neomacs_display_draw_border(struct NeomacsDisplay *handle,
                                 int x,
                                 int y,
                                 int width,
                                 int height,
                                 uint32_t color);

/**
 * Begin a new glyph row for the current window
 */
void neomacs_display_begin_row(struct NeomacsDisplay *handle,
                               int y,
                               int x,
                               int height,
                               int ascent,
                               int modeLine,
                               int headerLine);

/**
 * Add a character glyph to the current row
 */
void neomacs_display_add_char_glyph(struct NeomacsDisplay *handle,
                                    uint32_t charcode,
                                    uint32_t faceId,
                                    int pixelWidth,
                                    int ascent,
                                    int descent);

/**
 * Add a stretch (whitespace) glyph to the current row
 */
void neomacs_display_add_stretch_glyph(struct NeomacsDisplay *handle,
                                       int pixelWidth,
                                       int height,
                                       uint32_t faceId);

/**
 * Add an image glyph to the current row
 */
void neomacs_display_add_image_glyph(struct NeomacsDisplay *handle,
                                     uint32_t imageId,
                                     int pixelWidth,
                                     int pixelHeight);

/**
 * End the current row
 */
void neomacs_display_end_row(struct NeomacsDisplay *handle);

/**
 * Register or update a face
 * Colors are in 0xRRGGBB format
 */
void neomacs_display_set_face(struct NeomacsDisplay *handle,
                              uint32_t faceId,
                              uint32_t foreground,
                              uint32_t background,
                              const char *fontFamily,
                              uint16_t fontWeight,
                              int isItalic,
                              int fontSize,
                              int underlineStyle,
                              uint32_t underlineColor,
                              int boxType,
                              uint32_t boxColor,
                              int boxLineWidth,
                              int boxCornerRadius,
                              int strikeThrough,
                              uint32_t strikeThroughColor,
                              int overline,
                              uint32_t overlineColor,
                              int fontAscent,
                              int fontDescent,
                              int ulPosition,
                              int ulThickness);

/**
 * Set the frame/scene background color
 * Color is in 0xRRGGBB format
 */
void neomacs_display_set_background(struct NeomacsDisplay *handle, uint32_t color);

/**
 * Set the background alpha (transparency).
 * alpha: 0.0 (fully transparent) to 1.0 (fully opaque)
 */
void neomacs_display_set_background_alpha(struct NeomacsDisplay *handle,
                                           float alpha);

/**
 * Add a video glyph to the current row
 */
void neomacs_display_add_video_glyph(struct NeomacsDisplay *handle,
                                     uint32_t videoId,
                                     int pixelWidth,
                                     int pixelHeight);

/**
 * Load a video from file path (async - uses GStreamer)
 */
uint32_t neomacs_display_load_video(struct NeomacsDisplay *handle, const char *path);

/**
 * Play a loaded video
 */
int neomacs_display_video_play(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Pause a video
 */
int neomacs_display_video_pause(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Stop a video
 */
int neomacs_display_video_stop(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Set video loop mode (-1 for infinite)
 */
int neomacs_display_video_set_loop(struct NeomacsDisplay *handle, uint32_t videoId, int loopCount);

/**
 * Process pending video frames (call each frame)
 */
int neomacs_display_video_update(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Get video dimensions (works for pending and loaded videos)
 */
int neomacs_display_get_video_size(struct NeomacsDisplay *handle,
                                   uint32_t videoId,
                                   int *width,
                                   int *height);

/**
 * Load an image from a file path (stub)
 */
uint32_t neomacs_display_load_image(struct NeomacsDisplay *handle, const char *path);

/**
 * Load an image from raw bytes (stub)
 */
uint32_t neomacs_display_load_image_data(struct NeomacsDisplay *handle,
                                         const uint8_t *data,
                                         uintptr_t len);

/**
 * Load an image from raw bytes with optional scaling (stub)
 */
uint32_t neomacs_display_load_image_data_scaled(struct NeomacsDisplay *handle,
                                                const uint8_t *data,
                                                uintptr_t len,
                                                int maxWidth,
                                                int maxHeight);

/**
 * Load an image from raw ARGB32 pixel data (stub)
 */
uint32_t neomacs_display_load_image_argb32(struct NeomacsDisplay *handle,
                                           const uint8_t *data,
                                           int width,
                                           int height,
                                           int stride);

/**
 * Load an image from raw RGB24 pixel data (stub)
 */
uint32_t neomacs_display_load_image_rgb24(struct NeomacsDisplay *handle,
                                          const uint8_t *data,
                                          int width,
                                          int height,
                                          int stride);

/**
 * Load an image from a file path (async - returns ID immediately)
 */
uint32_t neomacs_display_load_image_file(struct NeomacsDisplay *handle, const char *path);

/**
 * Load an image from a file path with scaling (async)
 */
uint32_t neomacs_display_load_image_file_scaled(struct NeomacsDisplay *handle,
                                                const char *path,
                                                int maxWidth,
                                                int maxHeight);

/**
 * Load an image directly as texture (same as load_image_file)
 */
uint32_t neomacs_display_load_image_file_direct(struct NeomacsDisplay *handle, const char *path);

/**
 * Load an image directly as texture with scaling
 */
uint32_t neomacs_display_load_image_file_direct_scaled(struct NeomacsDisplay *handle,
                                                       const char *path,
                                                       int maxWidth,
                                                       int maxHeight);

/**
 * Get image dimensions (works for pending and loaded images)
 */
int neomacs_display_get_image_size(struct NeomacsDisplay *handle,
                                   uint32_t imageId,
                                   int *width,
                                   int *height);

/**
 * Query image file dimensions without loading (fast - reads header only)
 */
int neomacs_display_query_image_file_size(struct NeomacsDisplay *handle,
                                          const char *path,
                                          int *width,
                                          int *height);

/**
 * Free an image from cache
 */
int neomacs_display_free_image(struct NeomacsDisplay *handle, uint32_t imageId);

/**
 * Set a floating video at a specific screen position
 */
void neomacs_display_set_floating_video(struct NeomacsDisplay *handle,
                                        uint32_t videoId,
                                        int x,
                                        int y,
                                        int width,
                                        int height);

/**
 * Remove a floating video
 */
void neomacs_display_clear_floating_video(struct NeomacsDisplay *handle, uint32_t videoId);

/**
 * Set a floating image at a specific screen position
 */
void neomacs_display_set_floating_image(struct NeomacsDisplay *handle,
                                        uint32_t imageId,
                                        int x,
                                        int y,
                                        int width,
                                        int height);

/**
 * Remove a floating image
 */
void neomacs_display_clear_floating_image(struct NeomacsDisplay *handle, uint32_t imageId);

/**
 * Clear a rectangular area of the display
 */
void neomacs_display_clear_area(struct NeomacsDisplay *handle, int x, int y, int width, int height);

/**
 * Scroll blit pixels within the pixel buffer (for scroll optimization).
 * Copies pixels from from_y to to_y and clears the exposed region.
 * Used by scroll_run_hook to match Emacs's pixel buffer expectations.
 *
 * @param handle Display handle (unused in threaded mode)
 * @param x Left edge of scroll region
 * @param y Top edge of scroll region (unused, included for consistency)
 * @param width Width of scroll region
 * @param height Height of region to copy
 * @param from_y Source Y position (frame-relative)
 * @param to_y Destination Y position (frame-relative)
 * @param bg_r Background red component (0.0-1.0)
 * @param bg_g Background green component (0.0-1.0)
 * @param bg_b Background blue component (0.0-1.0)
 */
void neomacs_display_scroll_blit(struct NeomacsDisplay *handle,
                                 int x, int y, int width, int height,
                                 int from_y, int to_y,
                                 float bg_r, float bg_g, float bg_b);

/**
 * Clear only media glyphs (Image, Video, WebKit) in a rectangular area.
 * Called at the start of update_window_begin to clear stale media glyphs
 * before Emacs sends new positions.
 */
void neomacs_display_clear_media_in_area(struct NeomacsDisplay *handle, int x, int y, int width, int height);

/**
 * Clear all glyphs - used when frame layout changes
 */
void neomacs_display_clear_all_glyphs(struct NeomacsDisplay *handle);

/**
 * Clear all cursors
 */
void neomacs_display_clear_all_cursors(struct NeomacsDisplay *handle);

/**
 * Clear all borders (window dividers)
 */
void neomacs_display_clear_all_borders(struct NeomacsDisplay *handle);

/**
 * End frame and render
 * Returns 0 on success, 1 if layout changed, -1 on error
 */
int neomacs_display_end_frame(struct NeomacsDisplay *handle);

/**
 * Start smooth scroll animation
 */
void neomacs_display_smooth_scroll(struct NeomacsDisplay *handle,
                                   int windowId,
                                   float fromOffset,
                                   float toOffset);

/**
 * Set mouse pointer cursor shape.
 * Types: 1=default/arrow, 2=text/ibeam, 3=hand/pointer,
 *        4=crosshair, 5=h-resize, 6=v-resize, 7=hourglass
 */
void neomacs_display_set_mouse_cursor(struct NeomacsDisplay *handle,
                                       int cursor_type);

/**
 * Warp (move) the mouse pointer to pixel position (x, y).
 */
void neomacs_display_warp_mouse(struct NeomacsDisplay *handle,
                                 int x, int y);

/**
 * Popup menu item structure for FFI.
 */
struct CPopupMenuItem
{
  const char *label;
  const char *shortcut;
  int enabled;
  int separator;
  int submenu;
  int depth;
};

/**
 * Show a popup menu at position (x, y) with the given items.
 * The render thread renders the menu and sends a MenuSelection event.
 */
void neomacs_display_show_popup_menu(struct NeomacsDisplay *handle,
                                     int x, int y,
                                     const struct CPopupMenuItem *items,
                                     int item_count,
                                     const char *title,
                                     uint32_t fg_color,
                                     uint32_t bg_color);

/**
 * Hide the active popup menu.
 */
void neomacs_display_hide_popup_menu(struct NeomacsDisplay *handle);

/**
 * Show a tooltip at position (x, y) with the given text and colors.
 * Colors are in sRGB float format (0.0-1.0).
 */
void neomacs_display_show_tooltip(struct NeomacsDisplay *handle,
                                   float x, float y,
                                   const char *text,
                                   float fg_r, float fg_g, float fg_b,
                                   float bg_r, float bg_g, float bg_b);

/**
 * Hide the active tooltip.
 */
void neomacs_display_hide_tooltip(struct NeomacsDisplay *handle);

/**
 * Set the window title (threaded mode - sends to render thread)
 */
void neomacs_display_set_title(struct NeomacsDisplay *handle,
                                const char *title);

/**
 * Set fullscreen mode (threaded mode)
 * mode: 0=none, 1=width, 2=height, 3=both, 4=maximized
 */
void neomacs_display_set_fullscreen(struct NeomacsDisplay *handle,
                                     int mode);

/**
 * Minimize/iconify the window (threaded mode)
 */
void neomacs_display_set_minimized(struct NeomacsDisplay *handle,
                                    int minimized);

/**
 * Set window position (threaded mode)
 */
void neomacs_display_set_position(struct NeomacsDisplay *handle,
                                   int x, int y);

/**
 * Request window inner size change (threaded mode)
 */
void neomacs_display_request_size(struct NeomacsDisplay *handle,
                                      int width, int height);

/**
 * Set window decorations (threaded mode)
 */
void neomacs_display_set_decorated(struct NeomacsDisplay *handle,
                                    int decorated);

/**
 * Reset cursor blink (call when cursor moves)
 */
void neomacs_display_reset_cursor_blink(struct NeomacsDisplay *handle);

/**
 * Configure cursor blinking (enable/disable and interval)
 */
void neomacs_display_set_cursor_blink(struct NeomacsDisplay *handle,
                                       int enabled, int interval_ms);

/**
 * Configure cursor animation (smooth motion)
 */
void neomacs_display_set_cursor_animation(struct NeomacsDisplay *handle,
                                           int enabled, float speed);

/**
 * Configure all animation settings
 */
void neomacs_display_set_animation_config(struct NeomacsDisplay *handle,
                                           int cursor_enabled, float cursor_speed,
                                           uint8_t cursor_style, uint32_t cursor_duration_ms,
                                           int crossfade_enabled, uint32_t crossfade_duration_ms,
                                           int scroll_enabled, uint32_t scroll_duration_ms,
                                           uint32_t scroll_effect, uint32_t scroll_easing,
                                           float trail_size,
                                           uint32_t crossfade_effect, uint32_t crossfade_easing);

/**
 * Add per-window metadata for animation detection
 */
void neomacs_display_add_window_info(struct NeomacsDisplay *handle,
                                      int64_t window_id, uint64_t buffer_id,
                                      int64_t window_start,
                                      int64_t window_end,
                                      int64_t buffer_size,
                                      float x, float y, float width, float height,
                                      float mode_line_height,
                                      int selected,
                                      int is_minibuffer,
                                      float char_height,
                                      const char *buffer_file_name,
                                      int modified);

/**
 * Check if animations are active
 */
int neomacs_display_has_animations(struct NeomacsDisplay *handle);

/**
 * Get backend name
 */
const char *neomacs_display_backend_name(struct NeomacsDisplay *handle);

/**
 * Check if backend is initialized
 */
int neomacs_display_is_initialized(struct NeomacsDisplay *handle);

/**
 * Set the resize callback for winit windows.
 *
 * The callback will be invoked when the window is resized.
 */
void neomacs_display_set_resize_callback(ResizeCallbackFn callback, void *userData);

/**
 * Set callback for WebKit new window/tab requests
 */
void neomacs_display_webkit_set_new_window_callback(bool (*callback)(uint32_t,
                                                                     const char*,
                                                                     const char*));

/**
 * Set callback for WebKit page load events
 */
void neomacs_display_webkit_set_load_callback(void (*callback)(uint32_t, int, const char*));

/**
 * Initialize WebKit subsystem with EGL display
 */
int neomacs_display_webkit_init(struct NeomacsDisplay *handle, void *eglDisplay);

/**
 * Create a new WebKit view
 */
uint32_t neomacs_display_webkit_create(struct NeomacsDisplay *handle, int width, int height);

/**
 * Destroy a WebKit view
 */
int neomacs_display_webkit_destroy(struct NeomacsDisplay *handle, uint32_t viewId);

/**
 * Load a URI in a WebKit view
 */
int neomacs_display_webkit_load_uri(struct NeomacsDisplay *handle,
                                    uint32_t viewId,
                                    const char *uri);

/**
 * Go back in a WebKit view
 */
int neomacs_display_webkit_go_back(struct NeomacsDisplay *handle, uint32_t viewId);

/**
 * Go forward in a WebKit view
 */
int neomacs_display_webkit_go_forward(struct NeomacsDisplay *handle, uint32_t viewId);

/**
 * Reload a WebKit view
 */
int neomacs_display_webkit_reload(struct NeomacsDisplay *handle, uint32_t viewId);

/**
 * Resize a WebKit view
 */
int neomacs_display_webkit_resize(struct NeomacsDisplay *handle,
                                  uint32_t viewId,
                                  int width,
                                  int height);

/**
 * Execute JavaScript in a WebKit view
 */
int neomacs_display_webkit_execute_js(struct NeomacsDisplay *handle,
                                      uint32_t viewId,
                                      const char *script);

/**
 * Set a floating WebKit view position and size
 */
void neomacs_display_set_floating_webkit(struct NeomacsDisplay *handle,
                                         uint32_t webkitId,
                                         int x,
                                         int y,
                                         int width,
                                         int height);

/**
 * Hide a floating WebKit view
 */
void neomacs_display_hide_floating_webkit(struct NeomacsDisplay *handle, uint32_t webkitId);

/**
 * Find which floating webkit view is at the given coordinates
 */
int neomacs_display_webkit_at_position(struct NeomacsDisplay *handle,
                                       int x,
                                       int y,
                                       uint32_t *outWebkitId,
                                       int *outRelX,
                                       int *outRelY);

/**
 * Send keyboard event to WebKit view
 */
void neomacs_display_webkit_send_key(struct NeomacsDisplay *handle,
                                     uint32_t webkitId,
                                     uint32_t keyCode,
                                     uint32_t hardwareKeyCode,
                                     int pressed,
                                     uint32_t modifiers);

/**
 * Send pointer/mouse event to WebKit view
 */
void neomacs_display_webkit_send_pointer(struct NeomacsDisplay *handle,
                                         uint32_t webkitId,
                                         uint32_t eventType,
                                         int x,
                                         int y,
                                         uint32_t button,
                                         uint32_t state,
                                         uint32_t modifiers);

/**
 * Send scroll event to WebKit view
 */
void neomacs_display_webkit_send_scroll(struct NeomacsDisplay *handle,
                                        uint32_t webkitId,
                                        int x,
                                        int y,
                                        int deltaX,
                                        int deltaY);

/**
 * Click in WebKit view (convenience function)
 */
void neomacs_display_webkit_click(struct NeomacsDisplay *handle,
                                  uint32_t webkitId,
                                  int x,
                                  int y,
                                  uint32_t button);

/**
 * Get WebKit view title
 */
char *neomacs_display_webkit_get_title(struct NeomacsDisplay *handle, uint32_t webkitId);

/**
 * Get WebKit view URL
 */
char *neomacs_display_webkit_get_url(struct NeomacsDisplay *handle, uint32_t webkitId);

/**
 * Get WebKit view loading progress
 */
double neomacs_display_webkit_get_progress(struct NeomacsDisplay *handle, uint32_t webkitId);

/**
 * Check if WebKit view is loading
 */
int neomacs_display_webkit_is_loading(struct NeomacsDisplay *handle, uint32_t webkitId);

/**
 * Free a string returned by webkit_get_title or webkit_get_url
 */
void neomacs_display_webkit_free_string(char *s);

/**
 * Update WebKit view - pumps GLib main context to process events
 * This MUST be called regularly (e.g., every frame or via timer) for WebKit to render
 */
int neomacs_display_webkit_update(struct NeomacsDisplay *handle, uint32_t webkitId);

/**
 * Update all WebKit views - pumps GLib main context
 * Call this once per frame to process all webkit events
 */
int neomacs_display_webkit_update_all(struct NeomacsDisplay *handle);

/**
 * Add a WPE glyph to the current row
 */
void neomacs_display_add_wpe_glyph(struct NeomacsDisplay *handle,
                                   uint32_t viewId,
                                   int pixelWidth,
                                   int pixelHeight);

/**
 * Create a new window with the specified dimensions and title.
 *
 * Returns the window ID. The window will be created during the next poll_events call.
 * Returns 0 if the backend is not available.
 */
uint32_t neomacs_display_create_window(struct NeomacsDisplay *handle,
                                       int32_t width,
                                       int32_t height,
                                       const char *title);

/**
 * Destroy a window by its ID.
 */
void neomacs_display_destroy_window(struct NeomacsDisplay *handle, uint32_t windowId);

/**
 * Show or hide a window.
 */
void neomacs_display_show_window(struct NeomacsDisplay *handle, uint32_t windowId, bool visible);

/**
 * Set the title of a window.
 */
void neomacs_display_set_window_title(struct NeomacsDisplay *handle,
                                      uint32_t windowId,
                                      const char *title);

/**
 * Set the size of a window.
 */
void neomacs_display_set_window_size(struct NeomacsDisplay *handle,
                                     uint32_t windowId,
                                     int32_t width,
                                     int32_t height);

/**
 * Begin a frame for a specific window.
 *
 * Clears the window's scene to prepare for new content.
 */
void neomacs_display_begin_frame_window(struct NeomacsDisplay *handle, uint32_t windowId,
                                        float charWidth, float charHeight,
                                        float fontPixelSize);

/**
 * End a frame for a specific window and present it.
 *
 * Renders the window's scene to its surface and presents it.
 */
void neomacs_display_end_frame_window(struct NeomacsDisplay *handle, uint32_t windowId);

/* Note: neomacs_display_set_event_callback() and neomacs_display_poll_events() have been removed.
 * Events are now delivered via the threaded mode wakeup mechanism.
 * Use neomacs_display_drain_input() instead.
 */

/**
 * Set an animation configuration option (stub)
 */
int neomacs_display_set_animation_option(struct NeomacsDisplay *handle,
                                         const char *key,
                                         const char *value);

/**
 * Get an animation configuration option (stub)
 */
char *neomacs_display_get_animation_option(struct NeomacsDisplay *handle, const char *key);

/**
 * Free a string returned by neomacs_display_get_animation_option
 */
void neomacs_display_free_string(char *s);

/**
 * Update cursor animation state (stub)
 */
int neomacs_display_update_animation(struct NeomacsDisplay *handle, double dt);

/**
 * Check if animation needs continuous redraw (stub)
 */
int neomacs_display_animation_active(struct NeomacsDisplay *handle);

/**
 * Trigger a buffer transition animation (stub)
 */
int neomacs_display_start_buffer_transition(struct NeomacsDisplay *handle,
                                            const char *effect,
                                            int durationMs);

/**
 * Prepare for buffer transition (stub)
 */
int neomacs_display_prepare_buffer_transition(struct NeomacsDisplay *handle);

/**
 * Trigger buffer transition animation (stub)
 */
int neomacs_display_trigger_buffer_transition(struct NeomacsDisplay *handle);

/**
 * Check if buffer transition is ready (stub)
 */
int neomacs_display_has_transition_snapshot(struct NeomacsDisplay *handle);

/**
 * Initialize display in threaded mode
 *
 * Returns the wakeup pipe fd that Emacs should select() on,
 * or -1 on error.
 */
int neomacs_display_init_threaded(uint32_t width, uint32_t height, const char *title);

/**
 * Monitor info struct returned by neomacs_display_get_monitor_info.
 */
struct NeomacsMonitorInfo {
  int x;
  int y;
  int width;
  int height;
  double scale;
  int width_mm;
  int height_mm;
};

/**
 * Wait for monitor info to be available (with timeout).
 * Call after neomacs_display_init_threaded().
 * Returns number of monitors, or 0 on timeout.
 */
int neomacs_display_wait_for_monitors(void);

/**
 * Get the number of monitors available.
 */
int neomacs_display_get_monitor_count(void);

/**
 * Get info about a specific monitor by index.
 * Returns 1 on success, 0 on failure.
 */
int neomacs_display_get_monitor_info(int index, struct NeomacsMonitorInfo *info);

/**
 * Get the name of a monitor by index.
 * Returns a pointer to a string (valid until next call), or NULL.
 */
const char *neomacs_display_get_monitor_name(int index);

/**
 * Drain input events from render thread
 *
 * Returns number of events written to buffer.
 */
int neomacs_display_drain_input(struct NeomacsInputEvent *events, int maxEvents);

/**
 * Send frame glyphs to render thread
 */
void neomacs_display_send_frame(struct NeomacsDisplay *handle);

/**
 * Send command to render thread
 */
void neomacs_display_send_command(int cmdType,
                                  uint32_t id,
                                  uint32_t param1,
                                  uint32_t param2,
                                  const char *strParam);

/**
 * Shutdown threaded display
 */
void neomacs_display_shutdown_threaded(void);

/**
 * Get wakeup fd for threaded mode (for Emacs to select() on)
 */
int neomacs_display_get_threaded_wakeup_fd(void);

/**
 * Get display handle for threaded mode
 *
 * Returns the NeomacsDisplay handle for use with frame operations.
 * Returns NULL if threaded mode is not initialized.
 */
struct NeomacsDisplay *neomacs_display_get_threaded_handle(void);

/* ============================================================================
 * Scroll Bar API
 * ============================================================================ */

/**
 * Add a GPU-rendered scroll bar to the current frame.
 * @param horizontal  1 for horizontal, 0 for vertical
 * @param x, y        Frame-absolute position of the scroll bar track
 * @param width, height  Dimensions of the scroll bar track
 * @param thumb_start  Thumb start position (pixels from track start)
 * @param thumb_size   Thumb size in pixels
 * @param track_color  Track background color (0xRRGGBB)
 * @param thumb_color  Thumb color (0xRRGGBB)
 */
void neomacs_display_add_scroll_bar(struct NeomacsDisplay *handle,
                                     int horizontal,
                                     int x, int y,
                                     int width, int height,
                                     int thumb_start, int thumb_size,
                                     uint32_t track_color,
                                     uint32_t thumb_color);

/* ============================================================================
 * Terminal (neo-term) API
 * ============================================================================ */

/**
 * Create a new terminal.
 * mode: 0=Window, 1=Inline, 2=Floating
 * shell: optional shell path (NULL for default)
 * Returns terminal ID (>0 on success, 0 on failure).
 */
uint32_t neomacs_display_terminal_create(uint16_t cols, uint16_t rows,
                                          uint8_t mode, const char *shell);

/**
 * Write input data to a terminal (keyboard input from user).
 */
void neomacs_display_terminal_write(uint32_t terminal_id,
                                     const uint8_t *data, size_t len);

/**
 * Resize a terminal.
 */
void neomacs_display_terminal_resize(uint32_t terminal_id,
                                      uint16_t cols, uint16_t rows);

/**
 * Destroy a terminal.
 */
void neomacs_display_terminal_destroy(uint32_t terminal_id);

/**
 * Set floating terminal position and opacity.
 */
void neomacs_display_terminal_set_float(uint32_t terminal_id,
                                         float x, float y, float opacity);

/**
 * Get visible text from a terminal.
 * Returns a malloc'd C string (caller must free with free()).
 * Returns NULL on failure.
 */
char *neomacs_display_terminal_get_text(uint32_t terminal_id);

/* ============================================================================
 * Clipboard API
 * ============================================================================ */

/**
 * Set clipboard text.
 * Returns 0 on success, -1 on error.
 */
int neomacs_clipboard_set_text(const char *text);

/**
 * Get clipboard text.
 * Returns a string that must be freed with neomacs_clipboard_free_text(),
 * or NULL if clipboard is empty or an error occurred.
 */
char *neomacs_clipboard_get_text(void);

/**
 * Free a string returned by neomacs_clipboard_get_text().
 */
void neomacs_clipboard_free_text(char *text);

/**
 * Set primary selection text (X11/Wayland).
 * Returns 0 on success, -1 on error.
 */
int neomacs_primary_selection_set_text(const char *text);

/**
 * Get primary selection text (X11/Wayland).
 * Returns a string that must be freed with neomacs_clipboard_free_text(),
 * or NULL if the selection is empty or an error occurred.
 */
char *neomacs_primary_selection_get_text(void);

/**
 * Trigger a visual bell flash effect on the render thread.
 */
void neomacs_display_visual_bell(struct NeomacsDisplay *handle);

/**
 * Set frame identity for child frame support.
 * Called after begin_frame_window, before glyphs are added.
 */
void neomacs_display_set_frame_identity(struct NeomacsDisplay *handle,
                                        uint64_t frame_id,
                                        uint64_t parent_id,
                                        float parent_x,
                                        float parent_y,
                                        int z_order,
                                        float border_width,
                                        uint32_t border_color,
                                        int no_accept_focus,
                                        float background_alpha);

/**
 * Remove a child frame from the render thread.
 * Called when a child frame is deleted or unparented.
 */
void neomacs_display_remove_child_frame(struct NeomacsDisplay *handle,
                                        uint64_t frame_id);

/**
 * Request window attention (urgency hint / taskbar flash).
 * If urgent is non-zero, uses Critical type; otherwise Informational.
 */
void neomacs_display_request_attention(struct NeomacsDisplay *handle,
                                       int urgent);

/**
 * Enable or disable scroll indicators and focus ring overlay.
 */
void neomacs_display_set_scroll_indicators(struct NeomacsDisplay *handle,
                                            int enabled);

/**
 * Set the custom title bar height (0 = hidden, >0 = show).
 */
void neomacs_display_set_titlebar_height(struct NeomacsDisplay *handle,
                                          int height);

/**
 * Toggle FPS counter overlay.
 */
void neomacs_display_set_show_fps(struct NeomacsDisplay *handle,
                                   int enabled);

/**
 * Set window corner radius for borderless mode (0 = square).
 */
void neomacs_display_set_corner_radius(struct NeomacsDisplay *handle,
                                        int radius);

void neomacs_display_set_extra_spacing(struct NeomacsDisplay *handle,
                                        int line_spacing,
                                        int letter_spacing);

void neomacs_display_set_background_gradient(
    struct NeomacsDisplay *handle,
    int enabled,
    int top_r, int top_g, int top_b,
    int bottom_r, int bottom_g, int bottom_b);

void neomacs_display_set_scroll_bar_config(
    struct NeomacsDisplay *handle,
    int width,
    int thumb_radius,
    int track_opacity,
    int hover_brightness);

void neomacs_display_set_indent_guides(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_indent_guide_rainbow(
    struct NeomacsDisplay *handle,
    int enabled,
    int num_colors,
    int r1, int g1, int b1, int o1,
    int r2, int g2, int b2, int o2,
    int r3, int g3, int b3, int o3,
    int r4, int g4, int b4, int o4,
    int r5, int g5, int b5, int o5,
    int r6, int g6, int b6, int o6);

void neomacs_display_set_line_highlight(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_show_whitespace(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_inactive_dim(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity);

void neomacs_display_set_cursor_glow(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int radius,
    int opacity);

void neomacs_display_set_cursor_pulse(
    struct NeomacsDisplay *handle,
    int enabled,
    int speed,
    int min_opacity);

void neomacs_display_set_focus_mode(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity);

void neomacs_display_set_minimap(
    struct NeomacsDisplay *handle,
    int enabled,
    int width);

void neomacs_display_set_typing_ripple(
    struct NeomacsDisplay *handle,
    int enabled,
    int max_radius,
    int duration_ms);

void neomacs_display_set_search_pulse(
    struct NeomacsDisplay *handle,
    int enabled,
    int face_id);

void neomacs_display_set_zen_mode(
    struct NeomacsDisplay *handle,
    int enabled,
    int content_width_pct,
    int margin_opacity);

void neomacs_display_set_background_pattern(
    struct NeomacsDisplay *handle,
    int style,
    int spacing,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_cursor_color_cycle(
    struct NeomacsDisplay *handle,
    int enabled,
    int speed,
    int saturation,
    int lightness);

void neomacs_display_set_header_shadow(
    struct NeomacsDisplay *handle,
    int enabled,
    int intensity,
    int size);

void neomacs_display_set_line_animation(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms);

void neomacs_display_set_vignette(
    struct NeomacsDisplay *handle,
    int enabled,
    int intensity,
    int radius);

void neomacs_display_set_scroll_progress(
    struct NeomacsDisplay *handle,
    int enabled,
    int height,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_window_glow(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int radius,
    int intensity);

void neomacs_display_set_breadcrumb(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity);

void neomacs_display_set_title_fade(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms);

void neomacs_display_set_typing_speed(
    struct NeomacsDisplay *handle,
    int enabled);

void neomacs_display_set_border_transition(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int duration_ms);

void neomacs_display_set_accent_strip(
    struct NeomacsDisplay *handle,
    int enabled,
    int width);

void neomacs_display_set_frosted_glass(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity,
    int blur);

void neomacs_display_set_region_glow(
    struct NeomacsDisplay *handle,
    int enabled,
    int face_id,
    int radius,
    int opacity);

void neomacs_display_set_cursor_shadow(
    struct NeomacsDisplay *handle,
    int enabled,
    int offset_x,
    int offset_y,
    int opacity);

void neomacs_display_set_focus_ring(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int opacity,
    int dash_length,
    int speed);

void neomacs_display_set_window_mode_tint(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity);

void neomacs_display_set_window_watermark(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity,
    int threshold);

void neomacs_display_set_mode_line_transition(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms);

void neomacs_display_set_cursor_wake(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms,
    int scale_pct);

void neomacs_display_set_window_content_shadow(
    struct NeomacsDisplay *handle,
    int enabled,
    int size,
    int opacity);

void neomacs_display_set_click_halo(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int duration_ms,
    int max_radius);

void neomacs_display_set_scroll_velocity_fade(
    struct NeomacsDisplay *handle,
    int enabled,
    int max_opacity,
    int fade_ms);

void neomacs_display_set_minibuffer_highlight(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int opacity);

void neomacs_display_set_resize_padding(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms,
    int max_padding);

void neomacs_display_set_cursor_error_pulse(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int duration_ms);

void neomacs_display_set_edge_snap(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int duration_ms);

void neomacs_display_set_cursor_crosshair(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int opacity);

void neomacs_display_set_modified_indicator(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int width,
    int opacity);

void neomacs_display_set_stained_glass(
    struct NeomacsDisplay *handle,
    int enabled,
    int opacity,
    int saturation);

void neomacs_display_set_focus_gradient_border(
    struct NeomacsDisplay *handle,
    int enabled,
    int top_r, int top_g, int top_b,
    int bot_r, int bot_g, int bot_b,
    int width,
    int opacity);

void neomacs_display_set_cursor_magnetism(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ring_count,
    int duration_ms,
    int opacity);

void neomacs_display_set_depth_shadow(
    struct NeomacsDisplay *handle,
    int enabled,
    int layers,
    int offset,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_mode_line_gradient(
    struct NeomacsDisplay *handle,
    int enabled,
    int left_r, int left_g, int left_b,
    int right_r, int right_g, int right_b,
    int opacity);

void neomacs_display_set_corner_fold(
    struct NeomacsDisplay *handle,
    int enabled,
    int size,
    int r,
    int g,
    int b,
    int opacity);

void neomacs_display_set_frosted_border(
    struct NeomacsDisplay *handle,
    int enabled,
    int width,
    int opacity,
    int r,
    int g,
    int b);

void neomacs_display_set_line_number_pulse(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int intensity,
    int cycle_ms);

void neomacs_display_set_breathing_border(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int min_opacity,
    int max_opacity,
    int cycle_ms);

void neomacs_display_set_scanlines(
    struct NeomacsDisplay *handle,
    int enabled,
    int spacing,
    int opacity,
    int r,
    int g,
    int b);

void neomacs_display_set_cursor_comet(
    struct NeomacsDisplay *handle,
    int enabled,
    int trail_length,
    int fade_ms,
    int r,
    int g,
    int b,
    int opacity);

void neomacs_display_set_cursor_spotlight(
    struct NeomacsDisplay *handle,
    int enabled,
    int radius,
    int intensity,
    int r,
    int g,
    int b);

void neomacs_display_set_cursor_particles(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int count,
    int lifetime_ms,
    int gravity);

void neomacs_display_set_window_border_radius(
    struct NeomacsDisplay *handle,
    int enabled,
    int radius,
    int border_width,
    int r,
    int g,
    int b,
    int opacity);

void neomacs_display_set_typing_heatmap(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int fade_ms,
    int opacity);

void neomacs_display_set_theme_transition(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms);

void neomacs_display_set_wrap_indicator(
    struct NeomacsDisplay *handle,
    int enabled,
    int r,
    int g,
    int b,
    int opacity);

void neomacs_display_set_scroll_momentum(
    struct NeomacsDisplay *handle,
    int enabled,
    int fade_ms,
    int width);

void neomacs_display_set_text_fade_in(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms);

void neomacs_display_set_scroll_line_spacing(
    struct NeomacsDisplay *handle,
    int enabled,
    int max_spacing,
    int duration_ms);

void neomacs_display_set_cursor_trail_fade(
    struct NeomacsDisplay *handle,
    int enabled,
    int length,
    int fade_ms);

void neomacs_display_set_idle_dim(
    struct NeomacsDisplay *handle,
    int enabled,
    int delay_secs,
    int opacity,
    int fade_ms);

void neomacs_display_set_noise_grain(
    struct NeomacsDisplay *handle,
    int enabled,
    int intensity,
    int size);

void neomacs_display_set_padding_gradient(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int opacity,
    int width);

void neomacs_display_set_cursor_size_transition(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms);

void neomacs_display_set_window_switch_fade(
    struct NeomacsDisplay *handle,
    int enabled,
    int duration_ms,
    int intensity);

void neomacs_display_set_mode_line_separator(
    struct NeomacsDisplay *handle,
    int style,
    int r, int g, int b,
    int height);

void neomacs_display_set_inactive_tint(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int opacity);

void neomacs_display_set_matrix_rain(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int column_count,
    int speed,
    int opacity);

void neomacs_display_set_cursor_elastic_snap(
    struct NeomacsDisplay *handle,
    int enabled,
    int overshoot,
    int duration_ms);

void neomacs_display_set_frost_border_effect(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int width,
    int opacity);

void neomacs_display_set_cursor_ghost(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int count,
    int fade_ms,
    int drift,
    int opacity);

void neomacs_display_set_edge_glow(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int height,
    int opacity,
    int fade_ms);

void neomacs_display_set_rain_effect(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int drop_count,
    int speed,
    int opacity);

void neomacs_display_set_cursor_ripple_wave(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ring_count,
    int max_radius,
    int duration_ms,
    int opacity);

void neomacs_display_set_aurora(
    struct NeomacsDisplay *handle,
    int enabled,
    int r1, int g1, int b1,
    int r2, int g2, int b2,
    int height,
    int speed,
    int opacity);

/**
 * Configure heat distortion/shimmer effect along window edges.
 */
void neomacs_display_set_heat_distortion(
    struct NeomacsDisplay *handle,
    int enabled,
    int intensity,
    int speed,
    int edge_width,
    int opacity);

/**
 * Configure cursor lighthouse beam effect.
 */
void neomacs_display_set_cursor_lighthouse(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int beam_width,
    int rotation_speed,
    int beam_length,
    int opacity);

/**
 * Configure neon border glow effect.
 */
void neomacs_display_set_neon_border(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int intensity,
    int flicker,
    int thickness,
    int opacity);

/**
 * Configure cursor sonar ping effect.
 */
void neomacs_display_set_cursor_sonar_ping(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ring_count,
    int max_radius,
    int duration_ms,
    int opacity);

/**
 * Configure lightning bolt effect along window borders.
 */
void neomacs_display_set_lightning_bolt(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int frequency,
    int intensity,
    int opacity);

/**
 * Configure cursor orbit particles effect.
 */
void neomacs_display_set_cursor_orbit_particles(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int particle_count,
    int orbit_radius,
    int speed,
    int opacity);

/**
 * Configure animated plasma border effect.
 */
void neomacs_display_set_plasma_border(
    struct NeomacsDisplay *handle,
    int enabled,
    int r1, int g1, int b1,
    int r2, int g2, int b2,
    int width,
    int speed,
    int opacity);

/**
 * Configure cursor heartbeat pulse effect.
 */
void neomacs_display_set_cursor_heartbeat(
    struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int bpm,
    int max_radius,
    int opacity);

/**
 * Configure topographic contour effect.
 */
void neomacs_display_set_topo_contour(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int spacing,
    int speed,
    int opacity);

/**
 * Configure cursor metronome tick effect.
 */
void neomacs_display_set_cursor_metronome(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int tick_height,
    int fade_ms,
    int opacity);

/**
 * Configure constellation overlay effect.
 */
void neomacs_display_set_constellation(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int star_count,
    int connect_dist,
    int twinkle_speed,
    int opacity);

/**
 * Configure cursor radar sweep effect.
 */
void neomacs_display_set_cursor_radar(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int radius,
    int speed,
    int opacity);

/**
 * Configure kaleidoscope overlay effect.
 */
void neomacs_display_set_kaleidoscope(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int segments,
    int speed,
    int opacity);

/**
 * Configure cursor ripple ring effect.
 */
void neomacs_display_set_cursor_ripple_ring(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int max_radius,
    int ring_count,
    int speed,
    int opacity);

/**
 * Configure noise field overlay effect.
 */
void neomacs_display_set_noise_field(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int scale,
    int speed,
    int opacity);

/**
 * Configure cursor scope effect.
 */
void neomacs_display_set_cursor_scope(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int thickness,
    int gap,
    int opacity);

/**
 * Configure spiral vortex overlay effect.
 */
void neomacs_display_set_spiral_vortex(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int arms,
    int speed,
    int opacity);

/**
 * Configure cursor shockwave effect.
 */
void neomacs_display_set_cursor_shockwave(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int radius,
    int decay,
    int opacity);

/**
 * Configure diamond lattice overlay effect.
 */
void neomacs_display_set_diamond_lattice(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int cell_size,
    int shimmer_speed,
    int opacity);

/**
 * Configure cursor gravity well effect.
 */
void neomacs_display_set_cursor_gravity_well(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int field_radius,
    int line_count,
    int opacity);

/**
 * Configure tessellation overlay effect.
 */
void neomacs_display_set_tessellation(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int tile_size,
    int rotation,
    int opacity);

/**
 * Configure cursor water drop effect.
 */
void neomacs_display_set_cursor_water_drop(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ripple_count,
    int expand_speed,
    int opacity);

/**
 * Configure guilloche overlay effect.
 */
void neomacs_display_set_guilloche(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int curve_count,
    int wave_freq,
    int opacity);

/**
 * Configure cursor pixel dust effect.
 */
void neomacs_display_set_cursor_pixel_dust(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int dust_count,
    int scatter_speed,
    int opacity);

/**
 * Configure celtic knot overlay effect.
 */
void neomacs_display_set_celtic_knot(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int knot_scale,
    int weave_speed,
    int opacity);

/**
 * Configure cursor candle flame effect.
 */
void neomacs_display_set_cursor_candle_flame(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int flame_height,
    int flicker_speed,
    int opacity);

/**
 * Configure argyle pattern overlay effect.
 */
void neomacs_display_set_argyle_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int diamond_size,
    int line_width,
    int opacity);

/**
 * Configure cursor moth flame effect.
 */
void neomacs_display_set_cursor_moth_flame(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int moth_count,
    int orbit_speed,
    int opacity);

/**
 * Configure basket weave overlay effect.
 */
void neomacs_display_set_basket_weave(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int strip_width,
    int strip_spacing,
    int opacity);

/**
 * Configure cursor sparkler effect.
 */
void neomacs_display_set_cursor_sparkler(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int spark_count,
    int burn_speed,
    int opacity);

/**
 * Configure fish scale overlay effect.
 */
void neomacs_display_set_fish_scale(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int scale_size,
    int row_offset,
    int opacity);

/**
 * Configure cursor plasma ball effect.
 */
void neomacs_display_set_cursor_plasma_ball(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int tendril_count,
    int arc_speed,
    int opacity);

/**
 * Configure trefoil knot overlay effect.
 */
void neomacs_display_set_trefoil_knot(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int knot_size,
    int rotation_speed,
    int opacity);

/**
 * Configure cursor quill pen effect.
 */
void neomacs_display_set_cursor_quill_pen(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int trail_length,
    int ink_speed,
    int opacity);

/**
 * Configure herringbone pattern overlay effect.
 */
void neomacs_display_set_herringbone_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int tile_width,
    int tile_height,
    int opacity);

/**
 * Configure cursor aurora borealis effect.
 */
void neomacs_display_set_cursor_aurora_borealis(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int band_count,
    int shimmer_speed,
    int opacity);

/**
 * Configure target reticle overlay effect.
 */
void neomacs_display_set_target_reticle(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ring_count,
    int pulse_speed,
    int opacity);

/**
 * Configure cursor feather effect.
 */
void neomacs_display_set_cursor_feather(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int feather_count,
    int drift_speed,
    int opacity);

/**
 * Configure plaid pattern overlay effect.
 */
void neomacs_display_set_plaid_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int band_width,
    int band_spacing,
    int opacity);

/**
 * Configure cursor stardust effect.
 */
void neomacs_display_set_cursor_stardust(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int particle_count,
    int fall_speed,
    int opacity);

/**
 * Configure brick wall overlay effect.
 */
void neomacs_display_set_brick_wall(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int brick_width,
    int brick_height,
    int opacity);

/**
 * Configure cursor compass needle effect.
 */
void neomacs_display_set_cursor_compass_needle(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int needle_length,
    int spin_speed,
    int opacity);

/**
 * Configure sine wave overlay effect.
 */
void neomacs_display_set_sine_wave(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int amplitude,
    int wavelength,
    int speed,
    int opacity);

/**
 * Configure cursor galaxy effect.
 */
void neomacs_display_set_cursor_galaxy(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int star_count,
    int radius,
    int opacity);

/**
 * Configure rotating gear overlay effect.
 */
void neomacs_display_set_rotating_gear(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int gear_size,
    int rotation_speed,
    int opacity);

/**
 * Configure cursor prism effect.
 */
void neomacs_display_set_cursor_prism(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ray_count,
    int spread,
    int opacity);

/**
 * Configure crosshatch pattern overlay effect.
 */
void neomacs_display_set_crosshatch_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int line_spacing,
    int angle,
    int speed,
    int opacity);

/**
 * Configure cursor moth effect.
 */
void neomacs_display_set_cursor_moth(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int moth_count,
    int wing_size,
    int opacity);

/**
 * Configure concentric rings overlay effect.
 */
void neomacs_display_set_concentric_rings(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ring_spacing,
    int expansion_speed,
    int opacity);

/**
 * Configure cursor flame effect.
 */
void neomacs_display_set_cursor_flame(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int particle_count,
    int height,
    int opacity);

/**
 * Configure zigzag pattern overlay effect.
 */
void neomacs_display_set_zigzag_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int amplitude,
    int frequency,
    int speed,
    int opacity);

/**
 * Configure cursor crystal effect.
 */
void neomacs_display_set_cursor_crystal(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int facet_count,
    int radius,
    int opacity);

/**
 * Configure moiré pattern overlay effect.
 */
void neomacs_display_set_moire_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int line_spacing,
    int angle_offset,
    int speed,
    int opacity);

/**
 * Configure cursor lightning effect.
 */
void neomacs_display_set_cursor_lightning(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int bolt_count,
    int max_length,
    int opacity);

/**
 * Configure dot matrix overlay effect.
 */
void neomacs_display_set_dot_matrix(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int dot_spacing,
    int pulse_speed,
    int opacity);

/**
 * Configure cursor snowflake effect.
 */
void neomacs_display_set_cursor_snowflake(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int count,
    int fall_speed,
    int opacity);

/**
 * Configure sunburst pattern overlay effect.
 */
void neomacs_display_set_sunburst_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int ray_count,
    int speed,
    int opacity);

/**
 * Configure cursor firework effect.
 */
void neomacs_display_set_cursor_firework(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int particle_count,
    int burst_radius,
    int opacity);

/**
 * Configure honeycomb dissolve overlay effect.
 */
void neomacs_display_set_honeycomb_dissolve(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int cell_size,
    int dissolve_speed,
    int opacity);

/**
 * Configure cursor tornado effect.
 */
void neomacs_display_set_cursor_tornado(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int radius,
    int particle_count,
    int opacity);

/**
 * Configure wave interference overlay effect.
 */
void neomacs_display_set_wave_interference(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int wavelength,
    int source_count,
    int speed,
    int opacity);

/**
 * Configure cursor portal effect.
 */
void neomacs_display_set_cursor_portal(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int radius,
    int speed,
    int opacity);

/**
 * Configure chevron pattern overlay effect.
 */
void neomacs_display_set_chevron_pattern(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int spacing,
    int speed,
    int opacity);

/**
 * Configure cursor bubble effect.
 */
void neomacs_display_set_cursor_bubble(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int count,
    int rise_speed,
    int opacity);

/**
 * Configure hex grid overlay effect.
 */
void neomacs_display_set_hex_grid(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int cell_size,
    int pulse_speed,
    int opacity);

/**
 * Configure cursor sparkle burst effect.
 */
void neomacs_display_set_cursor_sparkle_burst(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int particle_count,
    int burst_radius,
    int opacity);

/**
 * Configure circuit board trace effect.
 */
void neomacs_display_set_circuit_trace(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int trace_width,
    int speed,
    int opacity);

/**
 * Configure cursor compass rose effect.
 */
void neomacs_display_set_cursor_compass(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int size,
    int speed,
    int opacity);

/**
 * Configure warp/distortion grid effect.
 */
void neomacs_display_set_warp_grid(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int density,
    int amplitude,
    int speed,
    int opacity);

/**
 * Configure cursor DNA helix trail effect.
 */
void neomacs_display_set_cursor_dna_helix(struct NeomacsDisplay *handle,
    int enabled,
    int r1, int g1, int b1,
    int r2, int g2, int b2,
    int radius,
    int speed,
    int opacity);

/**
 * Configure prism/rainbow edge effect.
 */
void neomacs_display_set_prism_edge(struct NeomacsDisplay *handle,
    int enabled,
    int width,
    int speed,
    int saturation,
    int opacity);

/**
 * Configure cursor pendulum swing effect.
 */
void neomacs_display_set_cursor_pendulum(struct NeomacsDisplay *handle,
    int enabled,
    int r, int g, int b,
    int arc_length,
    int damping,
    int opacity);

/**
 * Get dropped file paths (call after NEOMACS_EVENT_FILE_DROP).
 * Returns number of paths written to out_paths.
 * Each path must be freed with neomacs_display_free_dropped_path().
 */
int neomacs_display_get_dropped_files(char **out_paths, int max_paths);

/**
 * Free a path returned by neomacs_display_get_dropped_files().
 */
void neomacs_display_free_dropped_path(char *path);

/**
 * Get terminal title from most recent title change event.
 * Returns a C string that must be freed with
 * neomacs_display_free_dropped_path(), or NULL if none pending.
 */
char *neomacs_display_get_terminal_title(uint32_t terminal_id);

#endif  /* NEOMACS_DISPLAY_H */
